export const alertColors = {
  update: '#064789',
  success: '#388659',
  danger: '#FF3A3A',
};

export const lightMode = {
  dark: false,
  colors: {
    primary: '#6750a4',
    onPrimary: '#ffffff',
    primaryContainer: '#e9ddff',
    onPrimaryContainer: '#22005d',
    secondary: '#625b71',
    onSecondary: '#ffffff',
    secondaryContainer: '#e8def8',
    OnSecondaryContainer: '#1e192b',
    tertiary: '#7e5260',
    onTertiary: '#ffffff',
    tertiaryContainer: '#ffd9e3',
    onTertiaryContainer: '#31101d',
    background: '#fffbff',
    onBackground: '#1c1b1e',
    surface: '#fffbff',
    onSurface: '#1c1b1e',
    surfaceVariant: '#e7e0eb',
    onSurfaceVariant: '#49454e',
    outline: '#7a757f',
    alertColors,
  },
};

export const darkMode = {
  dark: true,
  colors: {
    primary: '#cfbcff',
    onPrimary: '#381e72',
    primaryContainer: '#4f378a',
    onPrimaryContainer: '#e9ddff',
    secondary: '#cbc2db',
    onSecondary: '#332d41',
    secondaryContainer: '#4a4458',
    OnSecondaryContainer: '#e8def8',
    tertiary: '#efb8c8',
    onTertiary: '#4a2532',
    tertiaryContainer: '#633b48',
    onTertiaryContainer: '#ffd9e3',
    background: '#1c1b1e',
    onBackground: '#e6e1e6',
    surface: '#1c1b1e',
    onSurface: '#e6e1e6',
    surfaceVariant: '#49454e',
    onSurfaceVariant: '#cac4cf',
    outline: '#948f99',
    alertColors,
  },
};
